# -*- coding: utf-8 -*-
"""StealthSKUs_Checklist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J16NKCW16jd7Xnn0YCRYd6hL7CVa1EW-
"""

import pandas as pd
from google.colab import files

# Upload the Stealth SKU import file
print("Please upload the Stealth SKU file.")
uploaded = files.upload()
main_filename = list(uploaded.keys())[0]
df_main = pd.read_excel(main_filename)

# Required attributes
required_columns = [
    "Material Bank SKU", "Batch Number", "Product Type", "Primary Child", "Product Websites", "Hide From Product View",
    "Stealth SKU", "Visibility", "MBID", "Manufacturer", "Attribute Set Code", "Taxonomy Node", "Product Categories",
    "Manufacturer Sku", "Product Name", "Color Name", "Material Url", "Price Range", "California Prop 65", "Serial Sku",
    "Retired Sku", "Commercial & Residential", "Indoor & Outdoor", "Is Fulfillment SKU"
]

# Ensure all required columns are present
missing_columns = [col for col in required_columns if col not in df_main.columns]
if missing_columns:
    print("Missing columns in the main file:", missing_columns)
else:
    print("All required columns are present.")

# Expected values validation (case-sensitive)
expected_values = {
    "Product Type": "simple",
    "Primary Child": "No",
    "Product Websites": "base",
    "Hide From Product View": "Yes",
    "Stealth SKU": "Yes",
    "Visibility": "Not Visible Individually",
    "Serial Sku": "No",
    "Retired Sku": "No",
    "Is Fulfillment SKU": "Magento Only"
}

for field, expected in expected_values.items():
    if field in df_main.columns:
        invalid_values = df_main[df_main[field] != expected]
        if not invalid_values.empty:
            print(f"Invalid values found in {field}:")
            print(invalid_values[[field]])

# Upload the SKU list file
print("Please upload the SKU list file.")
uploaded_sku = files.upload()
sku_filename = list(uploaded_sku.keys())[0]
df_sku = pd.read_excel(sku_filename) if sku_filename.endswith('.xlsx') else pd.read_csv(sku_filename)

# Validate Sample SKU presence in Manufacturer Sku
if "Sample SKU" in df_sku.columns and "Manufacturer Sku" in df_main.columns:
    sample_skus = set(df_sku["Sample SKU"].astype(str))
    manufacturer_skus = set(df_main["Manufacturer Sku"].astype(str))

    missing_skus = sample_skus - manufacturer_skus
    if missing_skus:
        print("Alert: The following Sample SKU(s) are in the SKU list file but not in the main file:")
        print(missing_skus)
    else:
        print("All Sample SKU values in the SKU list are present in the Manufacturer Sku field of the main file.")

    print(f"Count of distinct values in 'Sample SKU' field: {df_sku['Sample SKU'].nunique()}")